/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDutySwapRouteImport } from './routes/_authenticated/duty-swap'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedInvigilationRouteImport } from './routes/_authenticated/invigilation'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedSeatingRouteImport } from './routes/_authenticated/seating'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams.index'
import { Route as AuthenticatedExamsExamIdRouteImport } from './routes/_authenticated/exams.$examId'
import { Route as AuthenticatedFormsAFormRouteImport } from './routes/_authenticated/forms/a-form'
import { Route as AuthenticatedFormsBFormRouteImport } from './routes/_authenticated/forms/b-form'
import { Route as AuthenticatedFormsTenancyFormRouteImport } from './routes/_authenticated/forms/tenancy-form'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDutySwapRoute = AuthenticatedDutySwapRouteImport.update({
  id: '/duty-swap',
  path: '/duty-swap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvigilationRoute =
  AuthenticatedInvigilationRouteImport.update({
    id: '/invigilation',
    path: '/invigilation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeatingRoute = AuthenticatedSeatingRouteImport.update({
  id: '/seating',
  path: '/seating',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsExamIdRoute =
  AuthenticatedExamsExamIdRouteImport.update({
    id: '/exams/$examId',
    path: '/exams/$examId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormsAFormRoute = AuthenticatedFormsAFormRouteImport.update({
  id: '/forms/a-form',
  path: '/forms/a-form',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormsBFormRoute = AuthenticatedFormsBFormRouteImport.update({
  id: '/forms/b-form',
  path: '/forms/b-form',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormsTenancyFormRoute =
  AuthenticatedFormsTenancyFormRouteImport.update({
    id: '/forms/tenancy-form',
    path: '/forms/tenancy-form',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duty-swap': typeof AuthenticatedDutySwapRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/invigilation': typeof AuthenticatedInvigilationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/seating': typeof AuthenticatedSeatingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/forms/a-form': typeof AuthenticatedFormsAFormRoute
  '/forms/b-form': typeof AuthenticatedFormsBFormRoute
  '/forms/tenancy-form': typeof AuthenticatedFormsTenancyFormRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duty-swap': typeof AuthenticatedDutySwapRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/invigilation': typeof AuthenticatedInvigilationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/seating': typeof AuthenticatedSeatingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/forms/a-form': typeof AuthenticatedFormsAFormRoute
  '/forms/b-form': typeof AuthenticatedFormsBFormRoute
  '/forms/tenancy-form': typeof AuthenticatedFormsTenancyFormRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/duty-swap': typeof AuthenticatedDutySwapRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/invigilation': typeof AuthenticatedInvigilationRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/seating': typeof AuthenticatedSeatingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/teachers': typeof AuthenticatedTeachersRoute
  '/_authenticated/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/_authenticated/forms/a-form': typeof AuthenticatedFormsAFormRoute
  '/_authenticated/forms/b-form': typeof AuthenticatedFormsBFormRoute
  '/_authenticated/forms/tenancy-form': typeof AuthenticatedFormsTenancyFormRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/duty-swap'
    | '/emergency'
    | '/invigilation'
    | '/notifications'
    | '/rooms'
    | '/seating'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/exams/$examId'
    | '/forms/a-form'
    | '/forms/b-form'
    | '/forms/tenancy-form'
    | '/exams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/duty-swap'
    | '/emergency'
    | '/invigilation'
    | '/notifications'
    | '/rooms'
    | '/seating'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/exams/$examId'
    | '/forms/a-form'
    | '/forms/b-form'
    | '/forms/tenancy-form'
    | '/exams'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/duty-swap'
    | '/_authenticated/emergency'
    | '/_authenticated/invigilation'
    | '/_authenticated/notifications'
    | '/_authenticated/rooms'
    | '/_authenticated/seating'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/teachers'
    | '/_authenticated/exams/$examId'
    | '/_authenticated/forms/a-form'
    | '/_authenticated/forms/b-form'
    | '/_authenticated/forms/tenancy-form'
    | '/_authenticated/exams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duty-swap': {
      id: '/_authenticated/duty-swap'
      path: '/duty-swap'
      fullPath: '/duty-swap'
      preLoaderRoute: typeof AuthenticatedDutySwapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invigilation': {
      id: '/_authenticated/invigilation'
      path: '/invigilation'
      fullPath: '/invigilation'
      preLoaderRoute: typeof AuthenticatedInvigilationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seating': {
      id: '/_authenticated/seating'
      path: '/seating'
      fullPath: '/seating'
      preLoaderRoute: typeof AuthenticatedSeatingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$examId': {
      id: '/_authenticated/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/a-form': {
      id: '/_authenticated/forms/a-form'
      path: '/forms/a-form'
      fullPath: '/forms/a-form'
      preLoaderRoute: typeof AuthenticatedFormsAFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/b-form': {
      id: '/_authenticated/forms/b-form'
      path: '/forms/b-form'
      fullPath: '/forms/b-form'
      preLoaderRoute: typeof AuthenticatedFormsBFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/tenancy-form': {
      id: '/_authenticated/forms/tenancy-form'
      path: '/forms/tenancy-form'
      fullPath: '/forms/tenancy-form'
      preLoaderRoute: typeof AuthenticatedFormsTenancyFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDutySwapRoute: typeof AuthenticatedDutySwapRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedInvigilationRoute: typeof AuthenticatedInvigilationRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSeatingRoute: typeof AuthenticatedSeatingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRoute
  AuthenticatedExamsExamIdRoute: typeof AuthenticatedExamsExamIdRoute
  AuthenticatedFormsAFormRoute: typeof AuthenticatedFormsAFormRoute
  AuthenticatedFormsBFormRoute: typeof AuthenticatedFormsBFormRoute
  AuthenticatedFormsTenancyFormRoute: typeof AuthenticatedFormsTenancyFormRoute
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDutySwapRoute: AuthenticatedDutySwapRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedInvigilationRoute: AuthenticatedInvigilationRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSeatingRoute: AuthenticatedSeatingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRoute,
  AuthenticatedExamsExamIdRoute: AuthenticatedExamsExamIdRoute,
  AuthenticatedFormsAFormRoute: AuthenticatedFormsAFormRoute,
  AuthenticatedFormsBFormRoute: AuthenticatedFormsBFormRoute,
  AuthenticatedFormsTenancyFormRoute: AuthenticatedFormsTenancyFormRoute,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
