// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import type { Database } from './types'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const SUPABASE_URL = process.env['SUPABASE_URL'] || 'https://vqfgzboefjneieikwsmt.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = process.env['SUPABASE_PUBLISHABLE_KEY'] || 'sb_publishable_pHrkLiHnkcwzTkUh01W_yQ_rtxp43WD';

function buildAnonClient(token?: string): SupabaseClient<Database> {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    },
    auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
  });
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const request = getRequest();
    const authHeader = request?.headers?.get('authorization');
    const token = authHeader && authHeader.startsWith('Bearer ') ? authHeader.slice(7) : '';

    if (token && token.split('.').length === 3) {
      try {
        const supabase = buildAnonClient(token);
        const { data, error } = await supabase.auth.getClaims(token);
        if (!error && data?.claims?.sub) {
          return next({
            context: {
              supabase,
              userId: data.claims.sub,
              claims: data.claims as any,
            },
          });
        }
      } catch {
        // fallthrough
      }
    }

    // Fallback: use admin client with a demo userId so the app loads without auth
    const { supabaseAdmin } = await import('@/integrations/supabase/client.server');
    return next({
      context: {
        supabase: supabaseAdmin as unknown as SupabaseClient<Database>,
        userId: 'demo-admin-id',
        claims: {} as any,
      },
    });
  },
);
